//
//  APNS.swift
//  1MemorySprite
//
//  Created by sj on 16/01/2018.
//  Copyright © 2018 Apple. All rights reserved.
//

import Foundation
import UserNotifications
import UIKit


class APNS {
    static func registerAPNS(_ appDelegate: AppDelegate){
        if #available(iOS 10.0, *){
            let center = UNUserNotificationCenter.current()
            center.delegate = appDelegate
            center.requestAuthorization(options: [.alert, .badge, .sound]) { (granted, error) in
                if granted && error == nil {
                    //it has be executed in main thread, or error will occur
                    DispatchQueue.main.async {
                        UIApplication.shared.registerForRemoteNotifications()
                    }
                }
            }
        }
    }
    
    static func convertDeviceToken(_ deviceToken: Data){
        //get deviceToken generated by APNs
        //send the deviceToken combined with other infos, such as app version, userInfo, to provider server
        //deviceToken may change, remember to check and update by UserDefaults
        
        //convert deviceToken from 32byte to string
        let device = NSData(data: deviceToken)
        let deviceId = device.description.replacingOccurrences(of: "<", with: "").replacingOccurrences(of: ">", with: "").replacingOccurrences(of: " ", with: "")
        print("deviceToken", deviceId)

        //update deviceToken
        let oldDeviceToken = UserDefaults.standard.string(forKey: User.AccountInfo.deviceToken)
        if oldDeviceToken == nil || deviceId != oldDeviceToken {
            UserDefaults.standard.set(deviceId, forKey: User.AccountInfo.deviceToken)
            print("refresh deviceToken")
        }
    
    }

}
